name: Deploy to App Engine
on:
  push:
    branches:
      - main
      - test
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: cl-ssi/config
          token: ${{ secrets.CONFIG_REPO_TOKEN }}
          path: config
      - run: sudo apt install git-crypt
      - run: echo "${{ secrets.CRYPT_KEY_BASE64_CONFIG_REPO }}" | base64 -d > config-git-crypt.key
      - run: cd config && git-crypt unlock ../config-git-crypt.key
      - run: mkdir unisalud
      - uses: actions/checkout@v2
        with:
          repository: cl-ssi/unisalud
          path: unisalud
      - run: mv config/unisalud-test.yaml unisalud/app.yaml
        if: github.ref == 'refs/heads/test'
      - run: mv config/unisalud.yaml unisalud/app.yaml
        if: github.ref == 'refs/heads/main'
      - run: cd unisalud && composer install
      - run: |
          ls ${{ github.workspace }}/unisalud
