name: Deploy to App Engine
on:
  push:
    branches:
      - main
      - test
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
#       - name: Setup PHP with PECL extension
#         uses: shivammathur/setup-php@v2
#         with:
#           php-version: '7.3'
      - name: Check PHP Version
        run: php -v
      - run: mkdir unisalud
      - uses: actions/checkout@v2
        with:
          repository: GermanZun/unisalud_fork
          path: unisalud
      - run: cd unisalud && composer install
      - run: |
          ls ${{ github.workspace }}/unisalud
