name: Deploy to App Engine
on:
  push:
    branches:
      - main
      - test
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check PHP Version
        run: php -v
      - run: mkdir unisalud
      - uses: actions/checkout@v2
        with:
          repository: GermanZun/unisalud_fork
          path: unisalud
      - run: |
          ls ${{ github.workspace }}/unisalud
